<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C00EN1E" failures="2" tests="10" name="test" time="0.199" errors="0" timestamp="2021-06-22T21:05:01 PDT">
  <testcase classname="testing.ReturnFaildTestmanual" name="test2" time="0.023">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test1" time="0.023">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test1" time="0.001">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testing.ReturnFaildTestmanual.test1(ReturnFaildTestmanual.java:9)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test2" time="0.008">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testing.ReturnFaildTestmanual" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testing.ReturnFaildTestmanual.test2(ReturnFaildTestmanual.java:13)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- test -->
